"""add post media and user timezone

Revision ID: 70ea1d0d8b67
Revises: deac0055145f
Create Date: 2026-09-10 23:23:14.170789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ea1d0d8b67'
down_revision: Union[str, Sequence[str], None] = 'deac0055145f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('blob_url', sa.String(length=1000), nullable=False),
    sa.Column('blob_pathname', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['post_drafts.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_blob_pathname'), 'post_media', ['blob_pathname'], unique=True)
    op.create_index(op.f('ix_post_media_draft_id'), 'post_media', ['draft_id'], unique=False)
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_media_uploaded_by'), 'post_media', ['uploaded_by'], unique=False)
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_index(op.f('ix_post_media_uploaded_by'), table_name='post_media')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_index(op.f('ix_post_media_draft_id'), table_name='post_media')
    op.drop_index(op.f('ix_post_media_blob_pathname'), table_name='post_media')
    op.drop_table('post_media')
    # ### end Alembic commands ###
