"""create post drafts table

Revision ID: deac0055145f
Revises: 4be17d597539
Create Date: 2026-09-10 15:05:35.786703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deac0055145f'
down_revision: Union[str, Sequence[str], None] = '4be17d597539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_drafts_author_id'), 'post_drafts', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_drafts_post_id'), 'post_drafts', ['post_id'], unique=True)
    op.create_index(op.f('ix_post_drafts_slug'), 'post_drafts', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_drafts_slug'), table_name='post_drafts')
    op.drop_index(op.f('ix_post_drafts_post_id'), table_name='post_drafts')
    op.drop_index(op.f('ix_post_drafts_author_id'), table_name='post_drafts')
    op.drop_table('post_drafts')
    # ### end Alembic commands ###
